### ISSUE TITLE
アプリの主要機能のUIを考える

### ISSUE THREAD

**Issue by startaiyo** [a5chin/refrigerator#3]
## 概要
- iOSアプリにおける、今回実装予定の以下要件を満たすUIを考えてください
   - 冷蔵庫の中に残っているものが一覧で見れること
   - 食べ物のカテゴリによってタグ付けできること
   - 残っている食べ物とその重さを登録できる登録フォームがあること
   - 各食べ物を編集、削除可能であること

## 実装方針

* [ ]

## 完了基準

* [ ] 上記要件が全て満たされたUIが、figmaまたはその他わかる形で共有されていること。

**Comment by startaiyo** [comment]
[こちら](https://www.figma.com/file/wfEwSF9uU7wDo1jrwsCVmB/Untitled?type=design&node-id=0%3A1&mode=design&t=IvkIMZDAqSQqAAZ4-1)で作成しました！
(デザインだけなので、特にPRは投げてません)
コメントお願いします！！

**Comment by a5chin** [comment]
デザインありがとう！良い感じだと思う！

個人的には以下の 2 点変えるといいかなと思いました！どうかな？？
Figmaで追記しようとしたけど上手くできなかったから，また使い方教えてほしい...😭
- `+`ボタンで食品追加
- タイルも栄養素毎に色を変える

個人的な近いイメージ↓
![image](https://github.com/a5chin/refrigerator/assets/81167661/8e7090b9-a824-48e8-98fa-d145aba73506)

**Comment by startaiyo** [comment]
コメントめっちゃありがとう！！
フォーム小さくてどうしようって思ってたから、その手があったか！ってなってる笑
figmaは俺も使いたてであまり使い方わかっていなくて、、でも基本的な部分は教えられるはず、、！

**Comment by startaiyo** [comment]
ちなみに、一つの食品につき一つの主要な栄養素ってイメージ？？
Figmaに載せた例みたいに二つの栄養素があるとき、背景色どうしようと思って、、

**Comment by a5chin** [comment]
> ちなみに、一つの食品につき一つの主要な栄養素ってイメージ？？
> Figmaに載せた例みたいに二つの栄養素があるとき、背景色どうしようと思って、、

確かに...複数ある食品も存在する気がしているから，タグに関しては今のままがベストな気がする！
ありがとう！

**Comment by startaiyo** [comment]
了解！！とりあえず
・タグ、背景色は今のまま
・登録フォームは+ボタンから飛べるようにして実装
で作り直してみる！

**Comment by a5chin** [comment]
飛べるようにっていうのは個人的にはモーダルをイメージしてます！

**Comment by startaiyo** [comment]
[直してみた](https://www.figma.com/file/wfEwSF9uU7wDo1jrwsCVmB/Refrigerator?type=design&node-id=0-1&mode=design&t=6wyrnf4yyVhV9nbL-0)！こんな感じで大丈夫そうか確認お願いします！
ちなみにヘッダーの色は勝手にグラデーションっぽくしたけど、どんな感じがの色がいいとか希望ある？

**Comment by a5chin** [comment]
UI 良いと思います！！
それでいきましょう！

**Comment by startaiyo** [comment]
デザインが決まったのでclose
