### ISSUE TITLE
重さを更新する API の設計

### ISSUE THREAD

**Issue by a5chin** [a5chin/refrigerator#6]
## 概要
- 重さを更新する API の設計について，いくつか案があるので決めたい
  1. `UpdateWeight`の様な関数一つのみで加減算する
  2. `AddWeight`, `TakeWeight`, `UpdateWeight`の様なそれぞれの役割を持つ関数を作る
      - `AddWeight`: 重さを足す（食材を買った）時に使う
      - `TakeWeight`: 重さを減らす（食材を使った）時に使う
      - `UpdateWeight`: どのくらい重量が変化したかわからない（更新を忘れた）けど，現在の食材の重さと辻褄が合わない時に使う

## 実装方針
[ ]

## 完了基準
- [x] API の入出力が決まっていること

## 補足事項
他にも良案があれば教えてください！！

**Comment by startaiyo** [comment]
「更新」だけならUpdateだけでいいと思う！！
- REST API的な考え方に沿っている点
- 今はingredientsだけだけど、これからモデルを追加していくことを考えるとある程度統一した方がいいと思う点
から、ingredients限定の関数を作るよりそっちの方がいいかな、と思ったので！
ちなみにここは俺も迷いポイントなんだけど、モデル間での統一化をするならupdateIngredientsの方が良い気がする…？

**Comment by a5chin** [comment]
了解です！
じゃあ`UpdateIngredients`で行きます〜
- 入力
  - 食品名
  - 更新後の重さ
- 出力
  - Status
