### ISSUE TITLE
iOSフロントエンドをバックエンドと同じリポジトリに置くべきか？

### ISSUE THREAD

**Issue by startaiyo** [a5chin/refrigerator#7]
iOSのプロジェクトは動的に書き変わるコードが非常に多いため、バックエンドのコードとは別のリポジトリにおくべきかもしれない。
[こちら](https://magicode.io/84d010m08/articles/e7b7a8dce31f419aa751fffc3650a79d)を見た感じ、同じリポジトリにおくことはbad practiceであるように見える…？？
新たなリポジトリを作ったらcloseする。

**Comment by startaiyo** [comment]
https://github.com/startaiyo/Refrigerator_iOS
こちらに作ったので、close

**Comment by a5chin** [comment]
調査ありがとう！
